# CosmosCost Monitoring Configuration
owner: cosmoscost
repo: upptime

# Monitoring schedule
workflowSchedule:
  uptime: "*/5 * * * *"
  responseTime: "0,30 * * * *"
  graphs: "0 0 * * *"
  staticSite: "0 * * * *"

# Delay between checks to avoid rate limiting
delay: 1000

sites:
  # Core Application
  - name: CosmosCost Homepage
    url: https://cosmoscost.com
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000

  - name: Public Health Check
    url: https://cosmoscost.com/api/health/public
    expectedStatusCodes:
      - 200
    maxResponseTime: 2000

  - name: Dashboard
    url: https://cosmoscost.com/dashboard
    expectedStatusCodes:
      - 200
      - 307
    maxResponseTime: 2000

  - name: Authentication
    url: https://cosmoscost.com/auth/login
    expectedStatusCodes:
      - 200
    maxResponseTime: 2000

  - name: Admin Console
    url: https://cosmoscost.com/admin
    expectedStatusCodes:
      - 200
      - 307
    maxResponseTime: 2000

  # Marketing & Documentation
  - name: Documentation
    url: https://cosmoscost.com/docs
    expectedStatusCodes:
      - 200
    maxResponseTime: 1500

  - name: Pricing Page
    url: https://cosmoscost.com/pricing
    expectedStatusCodes:
      - 200
    maxResponseTime: 1500

  # External Dependencies
  - name: Supabase Service
    url: https://suuiylxptffjqhhtpwwc.supabase.co/rest/v1/
    expectedStatusCodes:
      - 200
      - 401
    maxResponseTime: 2000

  - name: Stripe API Status
    url: https://status.stripe.com
    expectedStatusCodes:
      - 200
    maxResponseTime: 2000

status-website:
  cname: status.cosmoscost.com
  logoUrl: https://cosmoscost.com/logo/cosmoscost-256.png
  name: CosmosCost Status
  theme: dark
  introTitle: "**CosmosCost** Cloud Cost Management Platform"
  introMessage: Monitor the real-time status of CosmosCost services and infrastructure.
  navbar:
    - title: Status
      href: /
    - title: CosmosCost
      href: https://cosmoscost.com
    - title: Documentation
      href: https://cosmoscost.com/docs
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  metaTags:
    - name: "og:title"
      content: "CosmosCost Status"
    - name: "og:description"
      content: "Real-time status and uptime monitoring for CosmosCost"
    - name: "robots"
      content: "noindex"
  customHeadHtml: |
    <style>
      :root {
        --body-background-color: #f5f5f5;
        --card-background-color: #ffffff;
      }
    </style>

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
